### ISSUE TITLE
What's the intended use case for gec?

### ISSUE THREAD

**Issue by chmac** [impredicative/gec#1]
I've read the commands and I get some sense of the idea. I can create an encrypted git repo, copied to both GitHub and GitLab, and then unmount / decrypt it via gocryptfs. Cool.

Is it intended to be used as a way of adding transparent encryption to git repositories? So instead of using `git commit ...` in my repo, I would use `gec commit` and then my code is encrypted before being shipped off to GitHub, etc.

It looks like a neat piece of software, I just couldn't figure out what the expected use case was.

**Comment by impredicative** [comment]
gec doesn't do very much. The expected use case is to keep files encrypted both at rest on one's computer and in the remotes. Some users really do want their files encrypted at rest on their computer too though when the files are not in use. For example, if the file contains one's Social Security Number or medical records which would qualify as personally identifiable information or other sensitive information, it is rational to want to keep it encrypted locally when it's not in use.

gec is not a way to add transparent encryption to git repos. Transparent encryption would imply that the files are stored only in a decrypted state on one's computer. Transparent encryption could alternatively be better for many use cases as it will more easily facilitate tracking which files changed in a commit. This is something that gec can try to do with a little effort, but at least it's not implemented.

If using gec, both `git commit` and `gec commit` will work largely the same. A trivial difference is that `gec commit` adds everything first using `git add`. gec always allows a fallback to git or gocryptfs. The files are already stored in an encrypted state before `commit` is run.

I cannot tell you which of your files you should or shouldn't encrypt and store in gh+gl. It works fine for finite collections of small to medium sized files. The size limits noted in the readme are applicable and enforced.

**Comment by chmac** [comment]
So the use case is keeping a folder of important data "safe". Both in the sense that it's backed up off my machine and that it's encrypted, both on my machine and when stored offsite. I effectively "unlock" the repo when I want to use it, do something with the files, then "lock" it again afterwards and it's back to "safe". Is that about the gist of it?

Seems interesting. I'm mostly on macOS so I tend to use an encrypted sparebundle for that. Similar tech I guess, but apple's own stuff, so not so easy to recover on another machine. Maybe this combo is a similar setup but more standard.

**Comment by impredicative** [comment]
That would indeed be the most fundamental use case. Having said that, the term "important" is of course subjective. It's up to the user what they use it for. If the user wants to use it for everything, subject to the size limits, then so be it.

Currently gec doesn't fully support macOS, and this is not a high priority either, but it is expected be fully supported after gec gets rewritten to be more platform independent. Currently it calls some Linux tools that may work slightly differently on macOS. I currently support Linux.

**Comment by chmac** [comment]
Great, thanks for the info. I have a much better sense of the aim now. 👍
